# docker-compose.yml
version: '3.8'

services:
  postgres:
    build: .
    container_name: task1-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  postgres_data: