version: '3.9'  # Updated version

services:
  db:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: AppUserPass1
    ports:
      - "5432:5432"

  pinger:
    build: .
    container_name: db_pinger
    depends_on:
      - db
    env_file:
      - .env